config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  scope module: :web do
    root 'home#index'

    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'
  end

  namespace :api do
    resources :checks, only: %i[create]
  end

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |type, msg|
      .alert.alert-dismissible.fade.show class="#{bootstrap_flash_class(type)}"
        = msg
        button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"

app/views/layouts/shared/_head.html.slim
title
  = content_for(:title) || 'GitHub Quality'
meta[name='viewport' content='width=device-width,initial-scale=1']
meta[name='mobile-web-app-capable' content='yes']
= csrf_meta_tags
= csp_meta_tag
= yield :head
link[rel='manifest' href='/manifest.json']
link[rel='icon' href='/icon.png' type='image/png']
link[rel='icon' href='/icon.svg' type='image/svg+xml']
link[rel='apple-touch-icon' href='/icon.png']
= stylesheet_link_tag 'bootstrap', 'data-turbo-track': 'reload'
= javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
- # rubocop:disable Rails/OutputSafety
= Sentry.get_trace_propagation_meta.html_safe
- # rubocop:enable Rails/OutputSafety

app/views/layouts/shared/_nav.html.slim
/ Nav panel
.container.mb-2
  .py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light
      / Brand
      = link_to t('layouts.application.title'), root_path, class: 'navbar-brand'

      / Toggler for mobile
      button.navbar-toggler(
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarContent"
        aria-controls="navbarContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      )
        span.navbar-toggler-icon

      / Nav panel content
      #navbarContent.collapse.navbar-collapse
        / Left side
        ul.navbar-nav.me-auto.mb-2.mb-md-0
          - if user_signed_in?
            li.nav-item
              = link_to t('layouts.nav.repositories'), repositories_path, class: 'nav-link'
        / Right side
        ul.navbar-nav.ms-auto.mb-2.mb-md-0
          - if user_signed_in?
            li.nav-item.dropdown
              a.nav-link.dropdown-toggle href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" class="nav-link"
                = current_user.email
              ul.dropdown-menu.dropdown-menu-end aria-labelledby="userDropdown"
                li
                  = button_to t('layouts.nav.log_out'), auth_logout_path, method: :delete, class: 'dropdown-item'
          - else
            li.nav-item.me-2
              = button_to t('layouts.nav.sign_in'), auth_request_path(:developer), data: { turbo: false }, class: 'btn btn-outline-primary' if Rails.env.development?
            li.nav-item.me-2
              = button_to auth_request_path(:github), data: { turbo: false }, class: 'btn btn-outline-primary' do
                = t('layouts.nav.sign_in_with')
                span.bi.bi-github.ms-1

          / Lang switch
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"
              = I18n.locale.upcase
            ul.dropdown-menu.dropdown-menu-end aria-labelledby="languageDropdown"
              - I18n.available_locales.each do |locale|
                li
                  = link_to t("language.name.#{locale}"), url_for(locale: locale), class: 'dropdown-item'