config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  scope module: :web do
    root 'home#index'

    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'
  end

  namespace :api do
    resources :checks, only: %i[create]
  end

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize

  REPOSITORIES_LIST_CACHE_KEY_PREFIX = 'github-repos'

  def self.cache_key_for_user_repos(user_id)
    "#{REPOSITORIES_LIST_CACHE_KEY_PREFIX}/#{user_id}"
  end

  belongs_to :user, inverse_of: :repositories
  has_many :checks, class_name: 'Repository::Check', inverse_of: :repository, dependent: :destroy

  validates :github_id, presence: true, uniqueness: true

  enumerize :language, in: %i[ruby javascript]

  private

  def invalidate_cache
    Rails.cache.delete(self.class.cache_key_for_user_repos(user_id))
  end
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository, inverse_of: :checks, touch: true
  has_many   :offenses,
             class_name: 'Repository::Offense',
             dependent: :destroy,
             inverse_of: :check,
             counter_cache: :offenses_count

  aasm whiny_transitions: false do
    state :pending, initial: true
    state :cloning, :checking, :finished, :failed

    event :clone_repo do
      transitions from: :pending, to: :cloning
    end

    event :check do
      transitions from: :cloning, to: :checking
    end

    event :finish do
      transitions from: :checking, to: :finished
    end

    event :fail do
      transitions from: %i[pending cloning checking], to: :failed
    end
  end
end

app/models/repository/offense.rb
# frozen_string_literal: true

class Repository::Offense < ApplicationRecord
  belongs_to :check, class_name: 'Repository::Check', counter_cache: true, inverse_of: :offenses
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

module Web
  class Repositories::ApplicationController < ApplicationController
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < ApplicationController
      before_action :authenticate_user!

      def show
        @repository = set_repository
        @check = @repository.checks.find(params[:id])

        authorize @check

        @offenses_grouped_by_files = @check.offenses.group_by(&:file_path)
      end

      def create
        @repository = set_repository
        authorize @repository, :check?

        @check = @repository.checks.build

        if @check.save
          CheckRepositoryJob.perform_later(@check.id)
          redirect_to repository_path(@repository), notice: t('checks.crud.create.success')
        else
          redirect_to repository_path(@repository), alert: t('checks.crud.create.failure')
        end
      end

      private

      def set_repository
        @repository = Repository.find(params[:repository_id])
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < ApplicationController
    before_action :authenticate_user!

    def index
      @repositories = current_user.repositories
    end

    def show
      @repository = Repository.find(params[:id])
      authorize @repository
    end

    def new
      @repository = Repository.new
      @repositories_list = fetch_repositories_list
    end

    def create
      @repository = current_user.repositories.find_or_initialize_by(repository_params)

      if @repository.persisted?
        flash[:warning] = t('repositories.crud.create.exists')
      elsif @repository.save
        flash[:notice] = t('repositories.crud.create.success')
        add_webhook = true
      else
        flash[:alert] = t('repositories.crud.create.failure')
        @repositories_list = fetch_repositories_list
        render :new, status: :unprocessable_entity
        return
      end

      UpdateRepositoryInfoJob.perform_later(@repository.id, add_webhook:)
      redirect_to repositories_path
    end

    private

    def fetch_repositories_list
      Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
        client = ApplicationContainer[:octokit_client][current_user.token]
        ::Repositories::FetchListService.new(client: client).call
      end
    end

    def cache_key
      Repository.cache_key_for_user_repos(current_user.id)
    end

    def repository_params
      params.require(:repository).permit(:github_id)
    end
  end
end

app/views/web/repositories/_form.html.slim
= simple_form_for repository do |f|

  .mb-3
    = f.input :github_id, hint: false, as: :select, required: true, collection: repositories_list
  = f.submit t('repositories.links.add'), class: 'btn btn btn-success'

app/views/web/repositories/index.html.slim
= content_for :title do
  = t('repositories.titles.all')

= link_to new_repository_path, class: 'btn btn-primary repositories-new-button my-2 py-3 w-100' do
  i.bi.bi-plus-circle.me-1
  = t('repositories.links.add')

.div.table-responsive.mb-4
  table.table.table-striped.table-borderless
    thead
      tr
        th{ scope = 'col' } = t('active_record.attributes.repository.name')
        th{ scope = 'col' } = t('active_record.attributes.repository.language')
        th{ scope = 'col' } = t('active_record.attributes.repository.state')
        th

    tbody
      - @repositories.each do |repository|
        tr
          td
            - if repository.name.present?
              = link_to repository.name, repository_path(repository)
            - else
              .d-flex.align-items-center
                .spinner-border.spinner-border-sm.text-primary[role="status" aria-hidden="true"]
                em.ms-2 loading…
          td = repository.language
          - check_passed = repository.checks.last&.passed
          td = check_passed.nil? ? t('checks.not_started') : check_passed

app/views/web/repositories/new.html.slim
= content_for :title do
  = t('repositories.titles.new')

== render 'form', repository: @repository, repositories_list: @repositories_list

br

div
  = link_to t('repositories.links.back'), repositories_path

app/views/web/repositories/show.html.slim
= content_for :title do
  = @repository.full_name

= link_to repository_checks_path(@repository), data: { turbo_method: :post }, class: 'btn btn-primary' do
    = t('repositories.links.check')

.table-responsive
  table.table.table-borderless.table-small-first-col
    colgroup
      col(style = "width: 200px;")
      col
    tbody
      tr
        th
          strong.me-2 = t('active_record.attributes.repository.name')
        td = @repository.full_name
      tr
        th
          strong.me-2 = t('active_record.attributes.repository.language')
        td = @repository.language
      tr
        th
          strong.me-2 = t('active_record.attributes.repository.created_at')
        td = l(@repository.created_at, format: :long)
      tr
        th
          strong.me-2 = t('active_record.attributes.repository.updated_at')
        td = l(@repository.updated_at, format: :long)
hr
  - if @repository.checks.any?
    table.table.table-striped.mt-4
      thead
        tr
          th[scope='col'] = t('active_record.attributes.check.id')
          th[scope='col'] = t('active_record.attributes.check.state')
          th[scope='col'] = t('active_record.attributes.check.commit_id')
          th[scope='col'] = t('active_record.attributes.check.passed')
          th[scope='col'] = t('active_record.attributes.check.created_at')
      tbody
        - @repository.checks.order(id: :desc).each do |check|
          tr
          td
            = link_to repository_check_path(@repository, check) do
              = check.id
          td = check.aasm.human_state
          td = link_to github_commit_url(@repository, check.commit_id) do
            = check.commit_id
          td = check.passed
          td = l(check.created_at, format: :short)